schema_version: 1

context:
  name: prefect_redis
  version: "0.2.12"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/prefect_redis-${{ version }}.tar.gz
  sha256: 92a19d607713239e20d146f42db0fcbc06895821e80091ba263fc8e7909b0bad

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=45
    - wheel
    - setuptools-scm >=6.2
    - pip
  run:
    - python >=${{ python_min }}
    - prefect >=3.4.24
    - redis-py >=6.0.0

tests:
  - python:
      imports:
        - prefect_redis
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: Prefect integrations with Redis.
  homepage: https://github.com/PrefectHQ/prefect-redis
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - saschwartz
    - e7b7
    - conrade-ctc
